### ISSUE TITLE
An empty page would be displayed when the number of total discussions is multiple of single page discussions

### ISSUE THREAD

**Issue by zephray** [cnVintage/cnVintage-Legacy#3]
JavaScript is awesome

**Comment by ntzyz** [comment]
IEEE 754 floating point is awesome

**Comment by ntzyz** [comment]
No we shouldn't blame JavaScript or IEEE floating point. The reason for this is that pages are calculated in the wrong way.
[https://github.com/cnVintage/cnVintage-Legacy/blob/master/handler/index.js#L119](https://github.com/cnVintage/cnVintage-Legacy/blob/master/handler/index.js#L119)
Assuming that we have 30 discussions, and number of single page discussions  is 10:
``` javascript
let maxPages = data.maxPages = Math.floor(data.topics.length / config.postsPerPage) + 1;
// => 30 / 10 + 1 => 4
```
Obviously we can not add one to the results when the number of total discussions is multiple of single page discussions. So, the code should be like this?
``` javascript
let maxPages = data.maxPages = Math.floor(data.topics.length / config.postsPerPage)
                             + data.topics.length % config.postsPerPage === 0 ? 0 : 1;
```
