### ISSUE TITLE
尝试注册了很多次，还是不行

### ISSUE THREAD

**Issue by ghost** [cnVintage/cnVintage-Legacy#9]
都是网络不太顺，请再试一次
500
POST https://www.cnvintage.org/register

Illuminate\Contracts\Validation\ValidationException:  in file /var/www/html/vendor/flarum/core/src/Core/Validator/AbstractValidator.php on line 64
Stack trace:
  1. Illuminate\Contracts\Validation\ValidationException->() /var/www/html/vendor/flarum/core/src/Core/Validator/AbstractValidator.php:64
  2. Flarum\Core\Validator\AbstractValidator->assertValid() /var/www/html/vendor/flarum/core/src/Core/Command/RegisterUserHandler.php:137
  3. Flarum\Core\Command\RegisterUserHandler->handle() /var/www/html/vendor/illuminate/bus/Dispatcher.php:202
  4. call_user_func() /var/www/html/vendor/illuminate/bus/Dispatcher.php:202
  5. Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() /var/www/html/vendor/illuminate/pipeline/Pipeline.php:139
  6. call_user_func() /var/www/html/vendor/illuminate/pipeline/Pipeline.php:139
  7. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /var/www/html/vendor/illuminate/pipeline/Pipeline.php:102
  8. call_user_func() /var/www/html/vendor/illuminate/pipeline/Pipeline.php:102
  9. Illuminate\Pipeline\Pipeline->then() /var/www/html/vendor/illuminate/bus/Dispatcher.php:204
 10. Illuminate\Bus\Dispatcher->dispatchNow() /var/www/html/vendor/illuminate/bus/Dispatcher.php:177
 11. Illuminate\Bus\Dispatcher->dispatch() /var/www/html/vendor/flarum/core/src/Api/Controller/CreateUserController.php:45
 12. Flarum\Api\Controller\CreateUserController->data() /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php:97
 13. Flarum\Api\Controller\AbstractSerializeController->handle() /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php:23
 14. Flarum\Api\Controller\AbstractCreateController->handle() /var/www/html/vendor/flarum/core/src/Api/Client.php:69
 15. Flarum\Api\Client->send() /var/www/html/vendor/flarum/core/src/Forum/Controller/RegisterController.php:60
 16. Flarum\Forum\Controller\RegisterController->handle() /var/www/html/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php:53
 17. Flarum\Http\Handler\ControllerRouteHandler->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:69
 18. Flarum\Http\Middleware\DispatchRoute->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 19. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 20. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 21. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/SetLocale.php:51
 22. Flarum\Http\Middleware\SetLocale->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 23. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 24. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 25. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php:36
 26. Flarum\Http\Middleware\AuthenticateWithSession->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 27. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 28. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 29. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php:39
 30. Flarum\Http\Middleware\RememberFromCookie->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 31. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 32. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 33. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/StartSession.php:48
 34. Flarum\Http\Middleware\StartSession->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 35. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 36. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 37. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php:31
 38. Flarum\Http\Middleware\ParseJsonBody->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 39. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 40. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 41. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php:61
 42. Flarum\Http\Middleware\HandleErrors->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 43. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 44. Zend\Stratigility\Dispatch->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php:160
 45. Zend\Stratigility\Next->__invoke() /var/www/html/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:111
 46. Zend\Stratigility\MiddlewarePipe->__invoke() /var/www/html/vendor/flarum/core/src/Http/AbstractServer.php:55
 47. Flarum\Http\AbstractServer->__invoke() /var/www/html/vendor/zendframework/zend-diactoros/src/Server.php:157
 48. Zend\Diactoros\Server->listen() /var/www/html/vendor/flarum/core/src/Http/AbstractServer.php:36
 49. Flarum\Http\AbstractServer->listen() /var/www/html/index.php:16

**Comment by zephray** [comment]
请反馈使用的用户名和邮箱。有可能是用户名不符合限制。

**Comment by ghost** [comment]
@zephray 用户名:mini536邮箱mini67@live.cn

**Comment by zephray** [comment]
经确认为使用的密码不符合规定。错误提示需要修改。
